trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
  - script: pip install robotframework robotframework-seleniumlibrary
    displayName: 'Install dependencies'
  - script: |
      robot -d results tests/
    displayName: 'Run Robot Framework Tests'
  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'Robot Framework'
      testResultsFiles: 'results/output.xml'
